import type { Language } from "@/lib/pdf-recommendations";

export type SmeBusinessRevivalPlanRow = {
  competencyId: string;
  label: string;
};

export type SmeBusinessRevivalDay = {
  day: number;
  phase: string;
  competencyId: string;
  focus: string;
  ceoAction: string;
  accountableOwner: string;
  proofRequired: string;
  metric: string;
  ceoDecisionQuestion: string;
  stopOrChange: string;
};

type SmeProfile = {
  id: string;
  en: string;
  ar: string;
  ownerEn: string;
  ownerAr: string;
  proofEn: string;
  proofAr: string;
  metricEn: string;
  metricAr: string;
  questionEn: string;
  questionAr: string;
  stopEn: string;
  stopAr: string;
  actionsEn: string[];
  actionsAr: string[];
};

const ALIASES: Record<string, string> = {
  strategic_direction_clarity: "strategic_direction_business_clarity",
  revenue_engine_predictability: "revenue_engine_sales_predictability",
  cash_flow_margins_control: "cash_flow_margins_financial_control",
  operations_systems_process: "operations_systems_process_discipline",
  leadership_decision_rhythm: "leadership_decision_making_rhythm",
  products_services_value_prop: "products_services_value_proposition",
  technology_data_visibility: "technology_data_management_visibility",
  risk_compliance_continuity: "risk_compliance_business_continuity",
};

const clean = (id: string) =>
  String(id || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, "")
    .replace(/-/g, "_");

const profiles: SmeProfile[] = [
  {
    id: "strategic_direction_business_clarity",
    en: "Strategic Direction & Business Clarity",
    ar: "الاتجاه الاستراتيجي ووضوح الشركة",
    ownerEn: "CEO",
    ownerAr: "الرئيس التنفيذي",
    proofEn: "A signed one-page direction map, decision filters, and a stop-doing list",
    proofAr: "خارطة اتجاه من صفحة واحدة معتمدة، ومعايير قرار، وقائمة بما يجب إيقافه",
    metricEn: "Percentage of major decisions aligned with the three agreed priorities",
    metricAr: "نسبة القرارات الرئيسية المتوافقة مع الأولويات الثلاث المتفق عليها",
    questionEn: "Does this decision strengthen our chosen customer, offer, and strategic position?",
    questionAr: "هل يعزز هذا القرار العميل المستهدف والعرض المختار والموقع الاستراتيجي للشركة؟",
    stopEn: "Stop approving work, offers, or projects that do not support the chosen direction.",
    stopAr: "إيقاف الموافقة على أعمال أو عروض أو مشاريع لا تخدم الاتجاه المختار.",
    actionsEn: [
      "List every active priority, initiative, offer, and target market competing for management attention.",
      "Identify the customer segment producing the strongest combination of fit, margin, and repeat demand.",
      "Name the three business outcomes that must be true twelve months from now.",
      "Choose the company’s primary customer, core problem, strongest offer, and reason to believe.",
      "Rank all current initiatives against strategic value, cash impact, capacity demand, and urgency.",
      "Cancel, pause, or delegate the lowest-value initiative consuming leadership attention.",
      "Write a one-page direction map covering where we play, how we win, and what we will not do.",
      "Turn the direction map into five decision filters for spending, hiring, marketing, and product choices.",
      "Test the direction map against three live decisions awaiting CEO approval.",
      "Align the leadership team on the top three priorities and the trade-offs behind them.",
      "Translate each priority into one owner, one ninety-day outcome, and one weekly measure.",
      "Review the offer portfolio and remove strategic contradictions or duplicate promises.",
      "Communicate the direction to the wider team and require each function to name its contribution.",
      "Install a weekly strategic review that examines drift, decisions, and resource conflicts.",
      "Approve the final direction map and lock the next-quarter stop-doing list.",
    ],
    actionsAr: [
      "احصر جميع الأولويات والمبادرات والعروض والأسواق المستهدفة التي تتنافس على اهتمام الإدارة.",
      "حدد شريحة العملاء التي تحقق أفضل مزيج من الملاءمة والهامش وتكرار الطلب.",
      "حدد ثلاث نتائج تجارية يجب أن تتحقق خلال اثني عشر شهرًا.",
      "اختر العميل الأساسي للشركة ومشكلته الرئيسية وأقوى عرض وسبب الثقة به.",
      "رتب المبادرات الحالية حسب القيمة الاستراتيجية والأثر النقدي والضغط على الطاقة التنفيذية والاستعجال.",
      "ألغِ أو أوقف مؤقتًا أو فوّض المبادرة الأقل قيمة التي تستهلك انتباه القيادة.",
      "اكتب خارطة اتجاه من صفحة واحدة توضح أين تنافس الشركة وكيف تفوز وما الذي لن تفعله.",
      "حوّل خارطة الاتجاه إلى خمسة معايير لاتخاذ قرارات الإنفاق والتوظيف والتسويق والمنتجات.",
      "اختبر خارطة الاتجاه على ثلاثة قرارات فعلية تنتظر موافقة الرئيس التنفيذي.",
      "وحّد فريق القيادة حول الأولويات الثلاث والمفاضلات التي تقف خلفها.",
      "حوّل كل أولوية إلى مسؤول ونتيجة مطلوبة خلال تسعين يومًا ومقياس أسبوعي.",
      "راجع محفظة العروض وأزل التناقضات الاستراتيجية أو الوعود المتكررة.",
      "اشرح الاتجاه للفريق واطلب من كل إدارة تحديد مساهمتها المباشرة.",
      "ثبّت مراجعة استراتيجية أسبوعية تكشف الانحراف وتعارض الموارد والقرارات المعلقة.",
      "اعتمد خارطة الاتجاه النهائية وثبّت قائمة ما يجب إيقافه للربع القادم.",
    ],
  },
  {
    id: "revenue_engine_sales_predictability",
    en: "Revenue Engine & Sales Predictability",
    ar: "محرك الإيرادات واستقرار المبيعات",
    ownerEn: "Head of Sales or revenue owner",
    ownerAr: "مدير المبيعات أو مسؤول الإيرادات",
    proofEn: "A stage-based revenue funnel, opportunity register, and weekly forecast",
    proofAr: "مسار إيرادات حسب المراحل وسجل فرص وتوقع أسبوعي",
    metricEn: "Qualified opportunity value, conversion by stage, sales-cycle length, and forecast accuracy",
    metricAr: "قيمة الفرص المؤهلة والتحويل حسب المرحلة ومدة دورة البيع ودقة التوقع",
    questionEn: "Which buyer evidence makes next month’s revenue credible rather than hopeful?",
    questionAr: "ما دليل العميل الذي يجعل إيرادات الشهر القادم موثوقة وليست مجرد تفاؤل؟",
    stopEn: "Stop counting unqualified inquiries, verbal optimism, or owner relationships as forecast revenue.",
    stopAr: "إيقاف احتساب الاستفسارات غير المؤهلة أو التفاؤل الشفهي أو علاقات المالك كإيراد متوقع.",
    actionsEn: [
      "Map the full revenue journey from lead source to qualification, proposal, decision, sale, and repeat purchase.",
      "Analyse the last twenty wins and losses by source, customer type, offer, value, and sales-cycle length.",
      "Define entry and exit evidence for every stage of the revenue funnel.",
      "Clean the active opportunity list and remove deals without a real problem, authority, timing, or next step.",
      "Calculate the opportunity volume and conversion required to hit the next ninety-day revenue target.",
      "Assign an owner and dated next action to every qualified opportunity.",
      "Create a weekly forecast split into committed, probable, upside, and at-risk revenue.",
      "Inspect the five largest opportunities for buyer evidence, decision access, and delivery capacity.",
      "Standardise follow-up timing and content for each stage of the buying journey.",
      "Measure conversion and delay by stage to find the largest revenue bottleneck.",
      "Correct the weakest stage with one script, checklist, offer adjustment, or approval rule.",
      "Create a reactivation list of dormant customers and opportunities with a relevant reason to return.",
      "Compare forecasted revenue with actual revenue and document the cause of every material variance.",
      "Install a weekly revenue meeting focused on evidence, blockers, decisions, and next actions.",
      "Approve the next thirty-day revenue commitments and remove unsupported assumptions.",
    ],
    actionsAr: [
      "ارسم رحلة الإيرادات كاملة من مصدر العميل المحتمل إلى التأهيل والعرض والقرار والبيع وتكرار الشراء.",
      "حلل آخر عشرين حالة فوز وخسارة حسب المصدر ونوع العميل والعرض والقيمة ومدة دورة البيع.",
      "حدد دليل الدخول والخروج لكل مرحلة في مسار الإيرادات.",
      "نظف قائمة الفرص النشطة واستبعد ما لا يتضمن مشكلة حقيقية أو صلاحية قرار أو توقيتًا أو خطوة تالية.",
      "احسب حجم الفرص ونسب التحويل اللازمة لتحقيق هدف الإيرادات خلال التسعين يومًا القادمة.",
      "عيّن مسؤولًا وخطوة تالية مؤرخة لكل فرصة مؤهلة.",
      "أنشئ توقعًا أسبوعيًا يفصل الإيراد المؤكد والمحتمل والإضافي والمعرض للخطر.",
      "افحص أكبر خمس فرص من حيث دليل العميل والوصول لصاحب القرار والقدرة على التسليم.",
      "وحّد توقيت المتابعة ومحتواها لكل مرحلة في رحلة الشراء.",
      "قس التحويل والتأخير حسب المرحلة لتحديد أكبر اختناق في الإيرادات.",
      "صحح أضعف مرحلة باستخدام نص أو قائمة فحص أو تعديل عرض أو قاعدة موافقة محددة.",
      "أنشئ قائمة لإعادة تنشيط العملاء والفرص المتوقفة بسبب مناسب للعودة.",
      "قارن الإيراد المتوقع بالإيراد الفعلي ووثق سبب كل انحراف جوهري.",
      "ثبّت اجتماع إيرادات أسبوعيًا يركز على الأدلة والعوائق والقرارات والخطوات التالية.",
      "اعتمد التزامات الإيرادات للثلاثين يومًا القادمة واحذف الافتراضات غير المدعومة.",
    ],
  },
  {
    id: "marketing_positioning_lead_quality",
    en: "Marketing Positioning & Lead Quality",
    ar: "التموضع التسويقي وجودة العملاء المحتملين",
    ownerEn: "Marketing lead",
    ownerAr: "مسؤول التسويق",
    proofEn: "A focused positioning statement, lead-quality scorecard, and channel decision",
    proofAr: "صياغة تموضع مركزة وبطاقة جودة للعملاء المحتملين وقرار واضح للقنوات",
    metricEn: "Qualified-lead rate, acquisition cost, conversion by channel, and poor-fit lead share",
    metricAr: "نسبة العملاء المحتملين المؤهلين وتكلفة الاستحواذ والتحويل حسب القناة ونسبة غير الملائمين",
    questionEn: "Are we attracting the customer we can serve profitably, or merely generating attention?",
    questionAr: "هل نجذب العميل الذي نستطيع خدمته بربحية أم نولد اهتمامًا بلا قيمة؟",
    stopEn: "Stop funding channels or messages that produce volume without fit, intent, or measurable conversion.",
    stopAr: "إيقاف تمويل القنوات أو الرسائل التي تنتج حجمًا بلا ملاءمة أو نية شراء أو تحويل قابل للقياس.",
    actionsEn: [
      "Profile the highest-value customers by problem, trigger, buying reason, margin, and retention.",
      "Compare current marketing messages with the words used by profitable customers.",
      "Define the ideal lead and the conditions that make a lead poor-fit.",
      "Score the last fifty leads by source, fit, intent, conversion, and value.",
      "Identify the message or channel creating the highest volume of poor-fit demand.",
      "Rewrite the core positioning around customer, painful problem, outcome, proof, and difference.",
      "Create one lead-qualification form that captures fit, urgency, authority, and expected value.",
      "Align marketing and sales on the exact definition of a qualified lead.",
      "Test the revised message in one priority channel with a controlled audience.",
      "Review landing pages and campaigns for promises the delivery team cannot consistently fulfil.",
      "Pause one low-quality campaign and redirect effort to the best-fit source.",
      "Build three proof assets based on outcomes achieved for ideal customers.",
      "Measure cost and conversion by channel rather than total lead volume.",
      "Install a weekly lead-quality review with marketing, sales, and delivery input.",
      "Approve the channel mix and message for the next thirty days based on qualified demand.",
    ],
    actionsAr: [
      "صف العملاء الأعلى قيمة حسب المشكلة ومحفز الشراء وسبب القرار والهامش والاستمرار.",
      "قارن رسائل التسويق الحالية بالكلمات التي يستخدمها العملاء المربحون.",
      "حدد مواصفات العميل المحتمل المثالي والشروط التي تجعل العميل غير ملائم.",
      "قيّم آخر خمسين عميلًا محتملًا حسب المصدر والملاءمة والنية والتحويل والقيمة.",
      "حدد الرسالة أو القناة التي تنتج أكبر حجم من الطلب غير الملائم.",
      "أعد صياغة التموضع حول العميل والمشكلة المؤلمة والنتيجة والدليل والاختلاف.",
      "أنشئ نموذج تأهيل يلتقط الملاءمة والاستعجال وصلاحية القرار والقيمة المتوقعة.",
      "وحّد تعريف العميل المحتمل المؤهل بين التسويق والمبيعات.",
      "اختبر الرسالة المعدلة في قناة ذات أولوية وعلى جمهور مضبوط.",
      "راجع صفحات الهبوط والحملات بحثًا عن وعود لا يستطيع فريق التسليم الوفاء بها بثبات.",
      "أوقف حملة منخفضة الجودة ووجّه الجهد إلى أفضل مصدر للعملاء الملائمين.",
      "أنشئ ثلاثة أدلة تسويقية مبنية على نتائج تحققت لعملاء مثاليين.",
      "قس التكلفة والتحويل حسب القناة بدل الاكتفاء بإجمالي عدد العملاء المحتملين.",
      "ثبّت مراجعة أسبوعية لجودة العملاء المحتملين بمشاركة التسويق والمبيعات والتسليم.",
      "اعتمد مزيج القنوات والرسالة للثلاثين يومًا القادمة وفق الطلب المؤهل.",
    ],
  },
  {
    id: "customer_experience_retention",
    en: "Customer Experience & Retention",
    ar: "تجربة العملاء والاحتفاظ بهم",
    ownerEn: "Customer experience or operations lead",
    ownerAr: "مسؤول تجربة العملاء أو العمليات",
    proofEn: "A mapped customer journey, recovery standard, and retention action list",
    proofAr: "رحلة عميل موثقة ومعيار للاستدراك وقائمة إجراءات للاحتفاظ",
    metricEn: "Repeat purchase, retention, referrals, complaints resolved, and reactivation",
    metricAr: "تكرار الشراء والاحتفاظ والإحالات والشكاوى المعالجة وإعادة التنشيط",
    questionEn: "At which moment do customers lose confidence, value, or a reason to return?",
    questionAr: "في أي لحظة يفقد العميل الثقة أو القيمة أو سبب العودة؟",
    stopEn: "Stop treating delivery completion as the end of the customer relationship.",
    stopAr: "إيقاف اعتبار اكتمال التسليم نهاية لعلاقة العميل.",
    actionsEn: [
      "Map the customer journey from promise and onboarding through delivery, support, renewal, and referral.",
      "Review ten recent customers and identify trust-building and trust-leaking moments.",
      "List every unresolved complaint, delay, refund, cancellation, and silent customer loss.",
      "Define the three service standards customers must experience consistently.",
      "Assign ownership for onboarding, proactive updates, issue recovery, and renewal contact.",
      "Contact five at-risk customers to understand the reason for disengagement.",
      "Create a recovery protocol covering acknowledgement, owner, remedy, deadline, and follow-up.",
      "Compare the sales promise with the actual delivery experience and close one material gap.",
      "Introduce a milestone check-in before the point where customers commonly become dissatisfied.",
      "Segment customers by value, risk, renewal date, and expansion potential.",
      "Build a reactivation offer or conversation for suitable dormant customers.",
      "Ask recent successful customers for structured feedback, proof, referral, or review.",
      "Measure the causes of churn and repeat purchase rather than relying on anecdotes.",
      "Install a weekly customer-health review covering risk, recovery, retention, and expansion.",
      "Approve the next thirty-day retention priorities and owners.",
    ],
    actionsAr: [
      "ارسم رحلة العميل من الوعد والتهيئة إلى التسليم والدعم والتجديد والإحالة.",
      "راجع عشرة عملاء حديثين وحدد لحظات بناء الثقة وتسريبها.",
      "احصر جميع الشكاوى والتأخيرات والمبالغ المستردة والإلغاءات وحالات الفقد الصامت.",
      "حدد ثلاثة معايير خدمة يجب أن يعيشها العميل بثبات.",
      "عيّن مسؤولية التهيئة والتحديث الاستباقي واستدراك المشكلات والتواصل للتجديد.",
      "تواصل مع خمسة عملاء معرضين للفقد لفهم سبب ابتعادهم.",
      "أنشئ بروتوكول استدراك يشمل الإقرار والمسؤول والحل والموعد والمتابعة.",
      "قارن وعد المبيعات بتجربة التسليم الفعلية وأغلق فجوة جوهرية واحدة.",
      "أدخل نقطة تواصل قبل المرحلة التي يبدأ عندها عدم رضا العملاء عادة.",
      "قسّم العملاء حسب القيمة والخطر وموعد التجديد وفرصة التوسع.",
      "أنشئ عرضًا أو محادثة لإعادة تنشيط العملاء المتوقفين الملائمين.",
      "اطلب من العملاء الناجحين ملاحظات منظمة أو دليل نتيجة أو إحالة أو تقييمًا.",
      "قس أسباب فقد العملاء وتكرار الشراء بدل الاعتماد على الانطباعات.",
      "ثبّت مراجعة أسبوعية لصحة العملاء تشمل الخطر والاستدراك والاحتفاظ والتوسع.",
      "اعتمد أولويات الاحتفاظ ومسؤوليها للثلاثين يومًا القادمة.",
    ],
  },
  {
    id: "cash_flow_margins_financial_control",
    en: "Cash Flow, Margins & Financial Control",
    ar: "التدفق النقدي والهوامش والرقابة المالية",
    ownerEn: "CEO with finance lead",
    ownerAr: "الرئيس التنفيذي مع المسؤول المالي",
    proofEn: "A rolling 13-week cash forecast, debtor-ageing actions, margin analysis, and approval controls",
    proofAr: "توقع نقدي متجدد لثلاثة عشر أسبوعًا وإجراءات أعمار الديون وتحليل الهوامش وضوابط الموافقة",
    metricEn: "Cash runway, overdue receivables, collection rate, gross and net margin, and cash conversion cycle",
    metricAr: "مدة كفاية النقد والذمم المتأخرة ونسبة التحصيل والهامش الإجمالي والصافي ودورة تحويل النقد",
    questionEn: "Which decision protects cash and margin without damaging the company’s ability to deliver?",
    questionAr: "أي قرار يحمي النقد والهامش دون الإضرار بقدرة الشركة على التسليم؟",
    stopEn: "Stop spending without approval, selling without margin visibility, and allowing overdue receivables to remain ownerless.",
    stopAr: "إيقاف الإنفاق بلا موافقة والبيع بلا وضوح للهامش وترك الذمم المتأخرة بلا مسؤول.",
    actionsEn: [
      "Build a rolling 13-week cash forecast using opening cash, expected receipts, committed payments, and weekly closing cash.",
      "Reconcile forecast assumptions against bank balances, invoices, payroll, tax, debt, and supplier commitments.",
      "Produce a debtor-ageing report and separate current, overdue, disputed, and high-risk receivables.",
      "Assign collection ownership, contact dates, promises to pay, and escalation rules for every overdue account.",
      "Set payment priorities protecting payroll, statutory obligations, critical suppliers, and revenue delivery.",
      "Review gross margin and net margin by offer, product, service line, and major customer.",
      "Identify work that creates revenue but destroys margin through discounting, rework, scope creep, or delivery cost.",
      "Introduce spending approval thresholds and require cash-impact evidence for non-essential commitments.",
      "Escalate overdue receivables that missed a promised payment date and decide hold, restructure, or recovery action.",
      "Calculate the cash conversion cycle and identify the largest delay in billing, collection, inventory, or supplier terms.",
      "Renegotiate one material term affecting deposits, milestones, payment timing, supplier credit, or inventory exposure.",
      "Model the working-capital impact of planned growth before approving more sales, hiring, stock, or delivery capacity.",
      "Compare actual weekly cash movement with the 13-week forecast and explain every material variance.",
      "Install a weekly cash-control meeting with named decisions, owners, and due dates.",
      "Approve the next four weeks of payments, collections, margin corrections, and cash-preservation decisions.",
    ],
    actionsAr: [
      "أنشئ توقعًا نقديًا متجددًا لثلاثة عشر أسبوعًا يشمل رصيد البداية والمتحصلات والمدفوعات الملتزم بها ورصيد الإغلاق الأسبوعي.",
      "طابق افتراضات التوقع مع الأرصدة البنكية والفواتير والرواتب والضرائب والديون والتزامات الموردين.",
      "أصدر تقرير أعمار الديون وافصل الذمم الحالية والمتأخرة والمتنازع عليها وعالية الخطر.",
      "عيّن مسؤول التحصيل وتواريخ التواصل ووعود السداد وقواعد التصعيد لكل حساب متأخر.",
      "رتب أولوية المدفوعات لحماية الرواتب والالتزامات النظامية والموردين الحرجين وتسليم الإيرادات.",
      "راجع الهامش الإجمالي والهامش الصافي حسب العرض والمنتج والخدمة والعميل الرئيسي.",
      "حدد الأعمال التي تحقق إيرادًا لكنها تدمر الهامش بسبب الخصم أو إعادة العمل أو توسع النطاق أو تكلفة التسليم.",
      "أدخل حدود موافقة للإنفاق واشترط بيان الأثر النقدي للالتزامات غير الأساسية.",
      "صعّد الذمم التي أخلفت وعد السداد وقرر الإيقاف أو إعادة الجدولة أو إجراء الاسترداد.",
      "احسب دورة تحويل النقد وحدد أكبر تأخير في الفوترة أو التحصيل أو المخزون أو شروط الموردين.",
      "أعد التفاوض على شرط جوهري يتعلق بالدفعة المقدمة أو المراحل أو توقيت السداد أو ائتمان المورد أو المخزون.",
      "احسب أثر النمو المخطط على رأس المال العامل قبل اعتماد مبيعات أو توظيف أو مخزون أو طاقة تسليم إضافية.",
      "قارن الحركة النقدية الفعلية أسبوعيًا بالتوقع لثلاثة عشر أسبوعًا وفسر كل انحراف جوهري.",
      "ثبّت اجتماع رقابة نقدية أسبوعيًا بقرارات ومسؤولين ومواعيد محددة.",
      "اعتمد مدفوعات وتحصيلات وتصحيحات الهوامش وقرارات حماية النقد للأسابيع الأربعة القادمة.",
    ],
  },
  {
    id: "operations_systems_process_discipline",
    en: "Operations, Systems & Process Discipline",
    ar: "العمليات والأنظمة وانضباط الإجراءات",
    ownerEn: "Operations lead",
    ownerAr: "مسؤول العمليات",
    proofEn: "A documented critical workflow, service standard, handoff map, and exception log",
    proofAr: "مسار عمل حرج موثق ومعيار خدمة وخريطة تسليم وسجل استثناءات",
    metricEn: "Cycle time, error and rework rate, on-time delivery, and owner interventions",
    metricAr: "زمن الدورة ونسبة الأخطاء وإعادة العمل والتسليم في الموعد وتدخلات المالك",
    questionEn: "Which process failure repeatedly consumes time, margin, or customer trust?",
    questionAr: "أي خلل تشغيلي يستهلك الوقت أو الهامش أو ثقة العميل بصورة متكررة؟",
    stopEn: "Stop accepting undocumented workarounds and repeated owner rescue as normal operations.",
    stopAr: "إيقاف قبول الحلول الارتجالية غير الموثقة وتدخل المالك المتكرر كتشغيل طبيعي.",
    actionsEn: [
      "List the five workflows most critical to revenue delivery and customer trust.",
      "Select the workflow causing the most delays, rework, complaints, or owner intervention.",
      "Map the current workflow from trigger to completion, including every handoff and approval.",
      "Measure cycle time, waiting time, errors, rework, and escalation points.",
      "Remove one unnecessary approval, duplicate entry, or unclear handoff.",
      "Define the minimum service and quality standard for each critical step.",
      "Assign a process owner responsible for performance and improvement.",
      "Document the workflow as a practical checklist usable by the people doing the work.",
      "Test the checklist on one live case and record every exception.",
      "Correct the highest-impact exception and update the process.",
      "Create escalation rules for delays, quality failures, customer risk, and capacity overload.",
      "Train the relevant team using a live case rather than a policy presentation.",
      "Measure the revised workflow against the original baseline.",
      "Install a weekly operations review covering flow, exceptions, ownership, and decisions.",
      "Approve the standard process and the next workflow to systemise.",
    ],
    actionsAr: [
      "احصر مسارات العمل الخمسة الأكثر تأثيرًا في تسليم الإيراد وثقة العميل.",
      "اختر المسار الذي يسبب أكبر تأخير أو إعادة عمل أو شكوى أو تدخل من المالك.",
      "ارسم المسار الحالي من نقطة البدء إلى الإكمال مع جميع عمليات التسليم والموافقات.",
      "قس زمن الدورة والانتظار والأخطاء وإعادة العمل ونقاط التصعيد.",
      "أزل موافقة غير ضرورية أو إدخالًا مكررًا أو عملية تسليم غامضة.",
      "حدد الحد الأدنى لمعيار الخدمة والجودة في كل خطوة حرجة.",
      "عيّن مالكًا للعملية مسؤولًا عن الأداء والتحسين.",
      "وثق المسار في قائمة فحص عملية يستطيع منفذو العمل استخدامها.",
      "اختبر قائمة الفحص على حالة فعلية وسجل جميع الاستثناءات.",
      "صحح الاستثناء الأعلى أثرًا وحدّث الإجراء.",
      "أنشئ قواعد تصعيد للتأخير وفشل الجودة وخطر العميل وزيادة الضغط على الطاقة.",
      "درّب الفريق المعني باستخدام حالة فعلية بدل عرض سياسة نظري.",
      "قس المسار المعدل مقارنة بخط الأساس الأصلي.",
      "ثبّت مراجعة عمليات أسبوعية تشمل التدفق والاستثناءات والمسؤولية والقرارات.",
      "اعتمد الإجراء القياسي وحدد مسار العمل التالي المطلوب تنظيمه.",
    ],
  },
  {
    id: "people_roles_accountability",
    en: "People, Roles & Accountability",
    ar: "الأفراد والأدوار والمساءلة",
    ownerEn: "CEO with functional leaders",
    ownerAr: "الرئيس التنفيذي مع مديري الإدارات",
    proofEn: "A role-accountability map, outcome scorecards, and documented commitments",
    proofAr: "خريطة أدوار ومساءلة وبطاقات نتائج والتزامات موثقة",
    metricEn: "Commitments completed on time, role clarity, overdue actions, and recurring escalations",
    metricAr: "الالتزامات المنجزة في موعدها ووضوح الأدوار والإجراءات المتأخرة والتصعيدات المتكررة",
    questionEn: "Who owns the outcome, what evidence is due, and what happens if the commitment is missed?",
    questionAr: "من يملك النتيجة وما الدليل المطلوب وماذا يحدث عند عدم الوفاء بالالتزام؟",
    stopEn: "Stop assigning shared ownership, accepting vague updates, and rescuing missed commitments without consequence.",
    stopAr: "إيقاف الملكية المشتركة والتحديثات الغامضة وإنقاذ الالتزامات المتأخرة بلا عواقب.",
    actionsEn: [
      "List the company’s critical outcomes and name the single role accountable for each.",
      "Identify duplicated authority, owner-only decisions, and work falling between roles.",
      "Rewrite the six most important roles around outcomes, decisions, and measures rather than tasks.",
      "Clarify who decides, who executes, who contributes, and who must be informed.",
      "Review overdue commitments and separate skill, capacity, clarity, and behaviour causes.",
      "Set one measurable ninety-day outcome for each leadership role.",
      "Create a weekly scorecard showing owner, commitment, due date, evidence, and status.",
      "Hold one accountability conversation using facts, impact, standard, support, and consequence.",
      "Remove one approval or task the CEO should no longer own.",
      "Match workload and capability to the outcomes expected from each role.",
      "Create an escalation rule for missed commitments and unresolved cross-functional dependencies.",
      "Recognise one example of clear ownership and correct one example of responsibility avoidance.",
      "Review whether incentives and consequences support the agreed outcomes.",
      "Install a weekly accountability review based on evidence rather than activity descriptions.",
      "Approve the role map and decide the hiring, development, delegation, or performance actions required.",
    ],
    actionsAr: [
      "احصر النتائج الحرجة للشركة وحدد دورًا واحدًا مسؤولًا عن كل نتيجة.",
      "حدد الصلاحيات المتكررة والقرارات المحتجزة لدى المالك والأعمال التي تسقط بين الأدوار.",
      "أعد كتابة أهم ستة أدوار حول النتائج والقرارات والمقاييس بدل المهام.",
      "وضح من يقرر ومن ينفذ ومن يساهم ومن يجب إبلاغه.",
      "راجع الالتزامات المتأخرة وافصل أسباب المهارة والطاقة والوضوح والسلوك.",
      "حدد نتيجة قابلة للقياس خلال تسعين يومًا لكل دور قيادي.",
      "أنشئ بطاقة أسبوعية توضح المسؤول والالتزام والموعد والدليل والحالة.",
      "نفذ محادثة مساءلة واحدة باستخدام الوقائع والأثر والمعيار والدعم والعاقبة.",
      "أزل موافقة أو مهمة واحدة يجب ألا تبقى لدى الرئيس التنفيذي.",
      "وازن عبء العمل والقدرة مع النتائج المتوقعة من كل دور.",
      "أنشئ قاعدة تصعيد للالتزامات الفائتة والاعتماد المتبادل غير المحسوم.",
      "قدّر نموذجًا واضحًا للملكية وصحح نموذجًا واحدًا للتهرب من المسؤولية.",
      "راجع ما إذا كانت الحوافز والعواقب تدعم النتائج المتفق عليها.",
      "ثبّت مراجعة مساءلة أسبوعية تعتمد على الدليل لا وصف النشاط.",
      "اعتمد خريطة الأدوار وقرر إجراءات التوظيف أو التطوير أو التفويض أو إدارة الأداء.",
    ],
  },
  {
    id: "leadership_decision_making_rhythm",
    en: "Leadership & Decision-Making Rhythm",
    ar: "القيادة وإيقاع اتخاذ القرار",
    ownerEn: "CEO and leadership team",
    ownerAr: "الرئيس التنفيذي وفريق القيادة",
    proofEn: "A decision log, leadership agenda, and documented decision rights",
    proofAr: "سجل قرارات وجدول قيادة وصلاحيات قرار موثقة",
    metricEn: "Decision cycle time, overdue decisions, reversed decisions, and actions closed",
    metricAr: "زمن اتخاذ القرار والقرارات المتأخرة والمتراجَع عنها والإجراءات المغلقة",
    questionEn: "What decision is required now, who has the authority, and when will it be reviewed?",
    questionAr: "ما القرار المطلوب الآن ومن يملك الصلاحية ومتى ستتم مراجعته؟",
    stopEn: "Stop recycling the same issue through meetings without a decision, owner, or review date.",
    stopAr: "إيقاف تدوير القضية نفسها في الاجتماعات بلا قرار أو مسؤول أو موعد مراجعة.",
    actionsEn: [
      "List the ten most important unresolved decisions currently slowing the business.",
      "Classify each decision by impact, urgency, reversibility, evidence needed, and authority.",
      "Identify decisions trapped with the CEO that should be delegated.",
      "Define decision rights for strategy, pricing, hiring, spending, customers, operations, and risk.",
      "Close one high-impact reversible decision within twenty-four hours.",
      "Create a decision log recording context, options, choice, owner, date, and review point.",
      "Redesign the leadership meeting around numbers, exceptions, decisions, and commitments.",
      "Remove status updates that can be read before the meeting.",
      "Test the new meeting on live issues and record decision cycle time.",
      "Review one poor past decision for process failure rather than blame.",
      "Introduce a short protocol for urgent decisions under pressure.",
      "Require every leadership action to have one owner, deadline, and proof.",
      "Review delegated decisions for quality without taking authority back.",
      "Install a fixed weekly and monthly leadership rhythm.",
      "Approve the decision-rights map and clear the remaining overdue decisions.",
    ],
    actionsAr: [
      "احصر أهم عشرة قرارات غير محسومة تبطئ الشركة حاليًا.",
      "صنف كل قرار حسب الأثر والاستعجال وقابلية التراجع والدليل المطلوب والصلاحية.",
      "حدد القرارات العالقة لدى الرئيس التنفيذي التي يجب تفويضها.",
      "حدد صلاحيات القرار للاستراتيجية والتسعير والتوظيف والإنفاق والعملاء والعمليات والمخاطر.",
      "احسم قرارًا عالي الأثر وقابلًا للتراجع خلال أربع وعشرين ساعة.",
      "أنشئ سجل قرارات يوثق السياق والخيارات والاختيار والمسؤول والتاريخ وموعد المراجعة.",
      "أعد تصميم اجتماع القيادة حول الأرقام والاستثناءات والقرارات والالتزامات.",
      "أزل تحديثات الحالة التي يمكن قراءتها قبل الاجتماع.",
      "اختبر الاجتماع الجديد على قضايا فعلية وسجل زمن اتخاذ القرار.",
      "راجع قرارًا سابقًا ضعيفًا بحثًا عن خلل العملية لا عن شخص يُلام.",
      "أدخل بروتوكولًا مختصرًا للقرارات العاجلة تحت الضغط.",
      "اشترط لكل إجراء قيادي مسؤولًا وموعدًا ودليلًا.",
      "راجع جودة القرارات المفوضة دون سحب الصلاحية.",
      "ثبّت إيقاع قيادة أسبوعيًا وشهريًا.",
      "اعتمد خريطة صلاحيات القرار وأغلق القرارات المتأخرة المتبقية.",
    ],
  },
  {
    id: "products_services_value_proposition",
    en: "Products, Services & Value Proposition",
    ar: "المنتجات والخدمات وعرض القيمة",
    ownerEn: "CEO with product or commercial lead",
    ownerAr: "الرئيس التنفيذي مع مسؤول المنتج أو الشؤون التجارية",
    proofEn: "An offer portfolio, profitability view, and evidence-based value proposition",
    proofAr: "محفظة عروض ورؤية للربحية وعرض قيمة قائم على الأدلة",
    metricEn: "Revenue and margin by offer, win rate, delivery effort, and customer outcome",
    metricAr: "الإيراد والهامش حسب العرض ونسبة الفوز وجهد التسليم ونتيجة العميل",
    questionEn: "Which offer creates the strongest customer outcome and economic value for the company?",
    questionAr: "أي عرض يحقق أقوى نتيجة للعميل وأفضل قيمة اقتصادية للشركة؟",
    stopEn: "Stop carrying low-value offers, custom work, or features that confuse buyers and consume margin.",
    stopAr: "إيقاف العروض منخفضة القيمة والعمل المخصص والخصائص التي تربك العميل وتستهلك الهامش.",
    actionsEn: [
      "List every product and service with revenue, margin, delivery effort, demand, and strategic fit.",
      "Identify the offers customers buy most easily and the outcomes they value most.",
      "Find offers that create complexity, rework, discount pressure, or weak margin.",
      "Interview or review evidence from five customers about why they chose, stayed, or left.",
      "Define the core customer problem and measurable outcome for each priority offer.",
      "Select the flagship offer the business should lead with.",
      "Rewrite its value proposition using problem, outcome, proof, scope, and next step.",
      "Clarify inclusions, exclusions, pricing logic, and change-control rules.",
      "Test the revised offer with live prospects or customers and capture objections.",
      "Remove one confusing option, feature, or custom variation.",
      "Package proof through case evidence, before-and-after measures, and customer language.",
      "Compare price and margin with the value and delivery risk of each offer.",
      "Decide which offers to grow, repair, bundle, automate, or retire.",
      "Install a monthly offer-performance review.",
      "Approve the simplified portfolio and flagship-offer growth plan.",
    ],
    actionsAr: [
      "احصر كل منتج وخدمة مع الإيراد والهامش وجهد التسليم والطلب والملاءمة الاستراتيجية.",
      "حدد العروض التي يشتريها العملاء بسهولة والنتائج التي يقدرونها أكثر.",
      "اكتشف العروض التي تخلق تعقيدًا أو إعادة عمل أو ضغط خصومات أو هامشًا ضعيفًا.",
      "قابل خمسة عملاء أو راجع أدلتهم لفهم سبب الاختيار أو الاستمرار أو المغادرة.",
      "حدد مشكلة العميل الأساسية والنتيجة القابلة للقياس لكل عرض ذي أولوية.",
      "اختر العرض الرئيسي الذي يجب أن تقود به الشركة.",
      "أعد صياغة قيمته حول المشكلة والنتيجة والدليل والنطاق والخطوة التالية.",
      "وضح ما يشمله العرض وما يستثنيه ومنطق التسعير وقواعد تغيير النطاق.",
      "اختبر العرض المعدل مع عملاء محتملين أو حاليين وسجل الاعتراضات.",
      "أزل خيارًا أو خاصية أو تعديلًا مخصصًا يسبب الارتباك.",
      "نظم الدليل من خلال حالات وقياسات قبل وبعد ولغة العملاء.",
      "قارن السعر والهامش بالقيمة وخطر التسليم لكل عرض.",
      "قرر العروض التي ستنمو أو تُصلح أو تُدمج أو تُؤتمت أو تُلغى.",
      "ثبّت مراجعة شهرية لأداء العروض.",
      "اعتمد المحفظة المبسطة وخطة نمو العرض الرئيسي.",
    ],
  },
  {
    id: "technology_data_management_visibility",
    en: "Technology, AI, Automation & Management Visibility",
    ar: "التقنية والذكاء الاصطناعي والأتمتة ووضوح الإدارة",
    ownerEn: "Operations or technology owner",
    ownerAr: "مسؤول العمليات أو التقنية",
    proofEn: "A management dashboard, data definitions, automation backlog, and access controls",
    proofAr: "لوحة إدارة وتعريفات بيانات وقائمة أتمتة وضوابط وصول",
    metricEn: "Data timeliness, dashboard completeness, manual hours removed, and automation reliability",
    metricAr: "حداثة البيانات واكتمال لوحة الإدارة والساعات اليدوية المخفضة وموثوقية الأتمتة",
    questionEn: "Which decision is currently delayed because management cannot see trustworthy information?",
    questionAr: "أي قرار يتأخر حاليًا لأن الإدارة لا ترى معلومات موثوقة؟",
    stopEn: "Stop adding tools, AI, or automation before defining the decision, data owner, process, and control.",
    stopAr: "إيقاف إضافة أدوات أو ذكاء اصطناعي أو أتمتة قبل تحديد القرار ومالك البيانات والإجراء والضابط.",
    actionsEn: [
      "List the ten numbers management needs weekly to control cash, revenue, customers, operations, people, and risk.",
      "Identify the source, owner, definition, frequency, and reliability of each number.",
      "Remove duplicate reports and reconcile conflicting definitions.",
      "Build a single management dashboard showing trend, target, variance, owner, and action.",
      "Select the manual process consuming the most time with clear rules and repeatable inputs.",
      "Map that process before choosing automation or artificial-intelligence support.",
      "Define privacy, approval, accuracy, and human-review controls for the selected use case.",
      "Run a small automation or artificial-intelligence pilot on low-risk work.",
      "Measure time saved, error rate, adoption, and decision improvement.",
      "Correct poor data capture at its operational source.",
      "Create alerts for material exceptions rather than more passive reports.",
      "Document access rights, backups, recovery, and ownership for critical systems.",
      "Train the responsible users and verify the new process with live evidence.",
      "Install a weekly dashboard review and monthly automation-benefit review.",
      "Approve the technology and automation backlog based on business impact, risk, and capacity.",
    ],
    actionsAr: [
      "حدد الأرقام العشرة التي تحتاجها الإدارة أسبوعيًا للسيطرة على النقد والإيرادات والعملاء والعمليات والأفراد والمخاطر.",
      "حدد مصدر كل رقم ومالكه وتعريفه وتكراره ودرجة موثوقيته.",
      "ألغِ التقارير المكررة ووحّد التعريفات المتعارضة.",
      "أنشئ لوحة إدارة واحدة تعرض الاتجاه والهدف والانحراف والمسؤول والإجراء.",
      "اختر العملية اليدوية الأكثر استهلاكًا للوقت ولها قواعد ومدخلات قابلة للتكرار.",
      "ارسم العملية قبل اختيار الأتمتة أو دعم الذكاء الاصطناعي.",
      "حدد ضوابط الخصوصية والموافقة والدقة والمراجعة البشرية للحالة المختارة.",
      "نفذ تجربة أتمتة أو ذكاء اصطناعي صغيرة على عمل منخفض الخطر.",
      "قس الوقت الموفر ونسبة الخطأ والتبني وتحسن القرار.",
      "صحح التقاط البيانات الضعيفة من مصدرها التشغيلي.",
      "أنشئ تنبيهات للاستثناءات الجوهرية بدل المزيد من التقارير الساكنة.",
      "وثق صلاحيات الوصول والنسخ الاحتياطي والاستعادة وملكية الأنظمة الحرجة.",
      "درّب المستخدمين المسؤولين وتحقق من الإجراء الجديد بأدلة فعلية.",
      "ثبّت مراجعة أسبوعية للوحة الإدارة ومراجعة شهرية لفائدة الأتمتة.",
      "اعتمد قائمة أولويات التقنية والأتمتة وفق أثر الأعمال والخطر والطاقة المتاحة.",
    ],
  },
  {
    id: "risk_compliance_business_continuity",
    en: "Risk, Compliance & Business Continuity",
    ar: "المخاطر والامتثال واستمرارية الأعمال",
    ownerEn: "CEO with risk or operations owner",
    ownerAr: "الرئيس التنفيذي مع مسؤول المخاطر أو العمليات",
    proofEn: "A risk register, control owners, continuity playbooks, and completed tests",
    proofAr: "سجل مخاطر ومسؤولو ضوابط وخطط استمرارية واختبارات مكتملة",
    metricEn: "Critical risks controlled, overdue mitigations, test results, and recovery readiness",
    metricAr: "المخاطر الحرجة المضبوطة وإجراءات المعالجة المتأخرة ونتائج الاختبار وجاهزية الاستعادة",
    questionEn: "Which single failure could stop revenue, delivery, compliance, or customer trust?",
    questionAr: "أي فشل واحد يمكن أن يوقف الإيراد أو التسليم أو الامتثال أو ثقة العميل؟",
    stopEn: "Stop accepting undocumented dependencies, expired obligations, and continuity assumptions without testing.",
    stopAr: "إيقاف قبول الاعتماديات غير الموثقة والالتزامات المنتهية وافتراضات الاستمرارية بلا اختبار.",
    actionsEn: [
      "List risks that could interrupt cash, revenue, operations, data, people, suppliers, compliance, or reputation.",
      "Score each risk by likelihood, impact, speed, detectability, and current control.",
      "Identify single points of failure involving the owner, key employee, supplier, system, customer, or licence.",
      "Confirm critical legal, regulatory, insurance, contract, tax, and employment obligations and due dates.",
      "Assign one owner and mitigation deadline to every critical risk.",
      "Create a continuity plan for the highest-impact interruption.",
      "Document emergency contacts, backups, alternative suppliers, manual workarounds, and decision authority.",
      "Test one backup, recovery, handover, or supplier alternative.",
      "Close the most serious gap found in the test.",
      "Review customer and supplier contracts for concentration, liability, renewal, and termination exposure.",
      "Protect critical knowledge with documented procedures and trained deputies.",
      "Create incident reporting and escalation rules.",
      "Re-score the top risks after mitigation and identify residual exposure.",
      "Install a monthly risk and continuity review.",
      "Approve the risk appetite, remaining mitigations, and next continuity test.",
    ],
    actionsAr: [
      "احصر المخاطر التي قد تعطل النقد أو الإيراد أو العمليات أو البيانات أو الأفراد أو الموردين أو الامتثال أو السمعة.",
      "قيّم كل خطر حسب الاحتمال والأثر والسرعة وقابلية الاكتشاف والضابط الحالي.",
      "حدد نقاط الفشل الفردية المتعلقة بالمالك أو الموظف الرئيسي أو المورد أو النظام أو العميل أو الترخيص.",
      "تحقق من الالتزامات القانونية والتنظيمية والتأمينية والتعاقدية والضريبية والعمالية ومواعيدها.",
      "عيّن مسؤولًا وموعد معالجة لكل خطر حرج.",
      "أنشئ خطة استمرارية لأعلى انقطاع محتمل أثرًا.",
      "وثق جهات الطوارئ والنسخ الاحتياطية والموردين البدلاء والإجراءات اليدوية وصلاحية القرار.",
      "اختبر نسخة احتياطية أو استعادة أو تسليمًا بديلًا أو موردًا بديلًا.",
      "أغلق أخطر فجوة كشفها الاختبار.",
      "راجع عقود العملاء والموردين بحثًا عن التركّز والمسؤولية والتجديد والإنهاء.",
      "احمِ المعرفة الحرجة بإجراءات موثقة وبدلاء مدربين.",
      "أنشئ قواعد للإبلاغ عن الحوادث وتصعيدها.",
      "أعد تقييم أعلى المخاطر بعد المعالجة وحدد التعرض المتبقي.",
      "ثبّت مراجعة شهرية للمخاطر والاستمرارية.",
      "اعتمد مستوى قبول المخاطر والمعالجات المتبقية واختبار الاستمرارية التالي.",
    ],
  },
  {
    id: "growth_readiness_scalability",
    en: "Growth Readiness & Scalability",
    ar: "جاهزية النمو وقابلية التوسع",
    ownerEn: "CEO with finance and operations leads",
    ownerAr: "الرئيس التنفيذي مع مسؤولي المالية والعمليات",
    proofEn: "A capacity model, growth economics, trigger plan, and controlled growth decision",
    proofAr: "نموذج طاقة واقتصاديات نمو وخطة محفزات وقرار نمو منضبط",
    metricEn: "Capacity utilisation, contribution margin, cash required for growth, and owner dependency",
    metricAr: "استخدام الطاقة وهامش المساهمة والنقد المطلوب للنمو واعتماد الشركة على المالك",
    questionEn: "Will the next unit of growth strengthen cash and capability, or amplify the current weakness?",
    questionAr: "هل ستقوي وحدة النمو التالية النقد والقدرة أم تضخم الضعف الحالي؟",
    stopEn: "Stop approving growth that lacks margin, working capital, capacity, systems, and accountable ownership.",
    stopAr: "إيقاف اعتماد نمو بلا هامش أو رأس مال عامل أو طاقة أو أنظمة أو مسؤولية واضحة.",
    actionsEn: [
      "Define the type of growth being considered: more customers, markets, offers, locations, channels, or capacity.",
      "Measure current capacity and the constraints in sales, delivery, people, cash, systems, and leadership.",
      "Calculate contribution margin and cash required for one additional unit of growth.",
      "Model the working-capital delay between spending for growth and collecting the resulting cash.",
      "Identify the process, role, supplier, system, or owner dependency most likely to break first.",
      "Set growth guardrails for margin, cash runway, service quality, and customer experience.",
      "Define trigger points for hiring, equipment, inventory, technology, and management capacity.",
      "Run a stress test at twenty-five and fifty percent higher demand.",
      "Correct the highest-risk bottleneck before increasing volume.",
      "Choose one controlled growth experiment with a defined budget, owner, customer segment, and success measure.",
      "Launch the experiment without committing irreversible fixed cost.",
      "Review customer quality, delivery performance, margin, cash, and team load from the experiment.",
      "Decide whether to scale, redesign, pause, or stop the experiment.",
      "Install a monthly growth-readiness review linking demand to capacity and cash.",
      "Approve the next growth gate only when the evidence shows the operating system can carry it.",
    ],
    actionsAr: [
      "حدد نوع النمو المقترح: عملاء أو أسواق أو عروض أو مواقع أو قنوات أو طاقة إضافية.",
      "قس الطاقة الحالية والقيود في المبيعات والتسليم والأفراد والنقد والأنظمة والقيادة.",
      "احسب هامش المساهمة والنقد المطلوب لوحدة نمو إضافية.",
      "احسب تأخر رأس المال العامل بين الإنفاق على النمو وتحصيل النقد الناتج عنه.",
      "حدد العملية أو الدور أو المورد أو النظام أو اعتماد المالك الأكثر احتمالًا للانهيار أولًا.",
      "ضع حدودًا للنمو تتعلق بالهامش ومدة كفاية النقد وجودة الخدمة وتجربة العميل.",
      "حدد محفزات التوظيف والمعدات والمخزون والتقنية والطاقة الإدارية.",
      "نفذ اختبار ضغط عند زيادة الطلب بنسبة خمسة وعشرين وخمسين بالمئة.",
      "صحح الاختناق الأعلى خطرًا قبل زيادة الحجم.",
      "اختر تجربة نمو منضبطة بميزانية ومسؤول وشريحة عميل ومقياس نجاح.",
      "أطلق التجربة دون الالتزام بتكلفة ثابتة يصعب التراجع عنها.",
      "راجع جودة العملاء والتسليم والهامش والنقد وضغط الفريق الناتج عن التجربة.",
      "قرر توسيع التجربة أو إعادة تصميمها أو إيقافها مؤقتًا أو إنهاءها.",
      "ثبّت مراجعة شهرية لجاهزية النمو تربط الطلب بالطاقة والنقد.",
      "اعتمد بوابة النمو التالية فقط عندما تثبت الأدلة قدرة نظام التشغيل على حملها.",
    ],
  },
];

export const SME_BUSINESS_REVIVAL_PROFILES: Record<string, SmeProfile> =
  Object.fromEntries(profiles.map((profile) => [profile.id, profile]));

function getProfile(id: string) {
  const normalized = clean(id);
  return SME_BUSINESS_REVIVAL_PROFILES[ALIASES[normalized] || normalized] || null;
}

function phaseLabel(blockIndex: number, lang: Language) {
  const number = blockIndex + 1;
  return lang === "ar" ? `المرحلة ${number} من ٦` : `Phase ${number} of 6`;
}

export function buildSmeBusinessRevival90DayPlan(
  weakestSix: SmeBusinessRevivalPlanRow[],
  lang: Language
): SmeBusinessRevivalDay[] {
  const selected = weakestSix.slice(0, 6);
  const days: SmeBusinessRevivalDay[] = [];

  selected.forEach((row, blockIndex) => {
    const profile = getProfile(row.competencyId);
    if (!profile) return;

    const ar = lang === "ar";
    const actions = ar ? profile.actionsAr : profile.actionsEn;
    const focus = row.label || (ar ? profile.ar : profile.en);
    const startDay = blockIndex * 15 + 1;

    actions.forEach((ceoAction, index) => {
      days.push({
        day: startDay + index,
        phase: phaseLabel(blockIndex, lang),
        competencyId: profile.id,
        focus,
        ceoAction,
        accountableOwner: ar ? profile.ownerAr : profile.ownerEn,
        proofRequired: ar ? profile.proofAr : profile.proofEn,
        metric: ar ? profile.metricAr : profile.metricEn,
        ceoDecisionQuestion: ar ? profile.questionAr : profile.questionEn,
        stopOrChange: ar ? profile.stopAr : profile.stopEn,
      });
    });
  });

  return days;
}
