import type { AssessmentDefinition } from "../assessment-definition";
import { smeBusinessHealthReportDefinition } from "./sme-report-definition";

const competencies = [
  ["strategic_direction_business_clarity", "strategic_direction_clarity", "Strategic Direction & Business Clarity", "الاتجاه الاستراتيجي ووضوح الأعمال"],
  ["revenue_engine_sales_predictability", "revenue_engine_predictability", "Revenue Engine & Sales Predictability", "محرك الإيرادات وقابلية التنبؤ بالمبيعات"],
  ["marketing_positioning_lead_quality", "marketing_positioning_lead_quality", "Marketing Positioning & Lead Quality", "التموضع التسويقي وجودة العملاء المحتملين"],
  ["customer_experience_retention", "customer_experience_retention", "Customer Experience & Retention", "تجربة العملاء والاحتفاظ بهم"],
  ["cash_flow_margins_financial_control", "cash_flow_margins_control", "Cash Flow, Margins & Financial Control", "التدفق النقدي والهوامش والرقابة المالية"],
  ["operations_systems_process_discipline", "operations_systems_process", "Operations, Systems & Process Discipline", "العمليات والأنظمة وانضباط الإجراءات"],
  ["people_roles_accountability", "people_roles_accountability", "People, Roles & Accountability", "الأفراد والأدوار والمساءلة"],
  ["leadership_decision_making_rhythm", "leadership_decision_rhythm", "Leadership & Decision-Making Rhythm", "القيادة وإيقاع اتخاذ القرار"],
  ["products_services_value_proposition", "products_services_value_prop", "Products, Services & Value Proposition", "المنتجات والخدمات وعرض القيمة"],
  ["technology_data_management_visibility", "technology_data_visibility", "Technology, Data & Management Visibility", "التقنية والبيانات ووضوح الإدارة"],
  ["risk_compliance_business_continuity", "risk_compliance_continuity", "Risk, Compliance & Business Continuity", "المخاطر والالتزام واستمرارية الأعمال"],
  ["growth_readiness_scalability", "growth_readiness_scalability", "Growth Readiness & Scalability", "جاهزية النمو وقابلية التوسع"],
] as const;

export const smeBusinessHealthAssessmentDefinition: AssessmentDefinition = {
  metadata: {
    id: "sme_business_health_mri",
    version: "1.0.0",
    name: "Advanced SME Business Health MRI",
    slug: "sme-business-health-mri",
    status: "published",
    type: "diagnostic",
    description: "Forensic business-health diagnostic for SME owners and general managers.",
    owner: "Career Labs AI",
    theme: { id: "sme-business-health", version: "1.0.0", reportThemeId: smeBusinessHealthReportDefinition.theme.id },
    icons: { primary: "building-heart" },
    tags: ["sme", "business-health", "mri"],
  },
  capabilities: {
    individualAvailability: true,
    corporateAvailability: false,
    managerDashboard: false,
    participantReport: true,
    managerReport: false,
    executiveReport: false,
    timed: true,
    bilingual: true,
    complimentaryAccess: true,
    developerTesting: true,
  },
  audience: {
    primary: "business-owner",
    supported: ["business-owner", "executive", "manager"],
    roleTags: ["sme-owner", "general-manager"],
  },
  accessPolicy: {
    channels: ["public", "authenticated", "entitlement", "developer"],
    authenticationRequired: false,
    individualEnabled: true,
    corporateEnabled: false,
    managerAccessEnabled: false,
    entitlementPolicies: [
      { type: "purchased", enabled: true, usage: "single-use", maximumUses: 1 },
      { type: "complimentary", enabled: true, usage: "single-use", maximumUses: 1 },
      { type: "internal-qa", enabled: true, usage: "single-use", maximumUses: 1 },
    ],
    tokenPolicy: { required: false, exchangeForSession: false, purpose: "Preserve the current SME beta-access behavior." },
  },
  localization: {
    defaultLocale: "en",
    supportedLocales: ["en", "ar"],
    requiredResourceKeys: ["assessment.name", "assessment.description"],
    locales: {
      en: { locale: "en", direction: "ltr", displayName: "English", resources: { "assessment.name": "Advanced SME Business Health MRI", "assessment.description": "A practical diagnostic across 12 business-health areas." } },
      ar: { locale: "ar", direction: "rtl", displayName: "العربية", resources: { "assessment.name": "Business Health MRI للشركات الصغيرة والمتوسطة", "assessment.description": "تشخيص عملي عبر 12 مجالًا لصحة الشركة." } },
    },
  },
  competencyModel: {
    id: "sme-business-health-areas",
    version: "1.0.0",
    competencies: competencies.map(([id, legacyId, en, ar], order) => ({
      id,
      order,
      label: { en, ar },
      aliases: legacyId === id ? [] : [legacyId],
      reportKey: id,
    })),
  },
  questionSource: {
    providerId: "legacy.supabase.questions",
    version: "1.0.0",
    kind: "database",
    questionCount: 96,
    timeLimitMinutes: 90,
    randomization: "questions-and-options",
  },
  scoringStrategy: {
    providerId: "legacy.actions.submitQuiz",
    strategyId: "live-option-score-weighted-percentage",
    version: "1.0.0",
    mode: "deterministic",
  },
  report: {
    providerId: "legacy.sme.report-adapter",
    version: "1.0.0",
    definitionId: smeBusinessHealthReportDefinition.id,
    supportedAudiences: ["participant"],
    definition: smeBusinessHealthReportDefinition,
  },
  pricing: { model: "free", individual: { currency: "AED", amountMinor: 0 } },
  features: {
    ninetyDayPlan: true,
    dailySchedule: true,
    strengthsAndWeaknesses: true,
    recommendations: true,
    charts: true,
    managerSections: false,
    executiveSections: false,
    pdfExport: true,
    docxExport: false,
    emailDelivery: true,
    aiModules: [],
  },
};
