"use client";
import { useMemo,useState } from "react";
import { ArrowLeft,ArrowRight,Building2,Check,Copy,KeyRound,Loader2,UserRound } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge"; import { Button } from "@/components/ui/button"; import { Card,CardContent,CardDescription,CardHeader,CardTitle } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Label } from "@/components/ui/label"; import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog"; import { RadioGroup,RadioGroupItem } from "@/components/ui/radio-group"; import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { ASSESSMENT_REPORT_VISIBILITIES,type AssessmentAccessType,type AssessmentFundingType,type AssessmentReportVisibility } from "@/modules/assessment-issuance-policy/assessment-issuance-policy";
import { EMPTY_ASSESSMENT_ACCESS_WIZARD,validateAssessmentAccessWizardStep,type AssessmentAccessCatalogItem,type AssessmentAccessWizardErrors,type AssessmentAccessWizardState } from "@/modules/assessment-access-center";
const steps=["Assessment","Recipient Type","Configure","Report Visibility","Confirmation"];
type Preview={expectedResult:Record<string,unknown>;warnings:string[]}; type Result={policyId:string;employeeAssessmentPath?:string;managerDashboardPath?:string;assessmentUrl?:string;[key:string]:unknown};
const labels:Record<string,string>={"participant-only":"Participant only","manager-only":"Manager / Company only","participant-and-manager":"Participant + Manager / Company","admin-only":"Admin only / no automatic visibility"};
function ErrorText({message}:{message?:string}){return message?<p role="alert" className="mt-1 text-sm font-semibold text-rose-700">{message}</p>:null;}
function Row({label,value}:{label:string;value:unknown}){if(value==null||value==="")return null;return <div className="grid gap-1 border-b py-3 last:border-0 sm:grid-cols-[180px_1fr]"><dt className="text-sm font-semibold text-slate-500">{label}</dt><dd className="break-all text-sm font-bold">{String(value)}</dd></div>;}
function Field({id,label,value,onChange,error,type="text",disabled=false}:{id:string;label:string;value:string;onChange:(v:string)=>void;error?:string;type?:string;disabled?:boolean}){return <div><Label htmlFor={id} className="font-bold">{label}</Label><Input id={id} type={type} value={value} onChange={e=>onChange(e.target.value)} disabled={disabled} className="mt-2 h-11" aria-invalid={!!error}/><ErrorText message={error}/></div>;}
type CompanyOption={id:string;name:string;billing_email:string;manager_name?:string|null;package_size:number;credits_balance:number};
export function AssessmentAccessCenter({assessments,companies=[]}:{assessments:AssessmentAccessCatalogItem[];companies?:CompanyOption[]}){
 const [started,setStarted]=useState(false),[step,setStep]=useState(1),[state,setState]=useState<AssessmentAccessWizardState>(EMPTY_ASSESSMENT_ACCESS_WIZARD),[errors,setErrors]=useState<AssessmentAccessWizardErrors>({}),[operationId,setOperationId]=useState(""),[preview,setPreview]=useState<Preview|null>(null),[issued,setIssued]=useState<Result|null>(null),[confirm,setConfirm]=useState(false),[busy,setBusy]=useState(false),[actionError,setActionError]=useState("");
 const assessment=useMemo(()=>assessments.find(a=>a.id===state.assessmentId),[assessments,state.assessmentId]);
 const selectedCompany=useMemo(()=>companies.find(c=>c.id===state.existingCompanyId),[companies,state.existingCompanyId]);
 const update=<K extends keyof AssessmentAccessWizardState>(key:K,value:AssessmentAccessWizardState[K])=>{setState(s=>({...s,[key]:value}));setErrors(e=>({...e,[key]:undefined}));setPreview(null);setIssued(null);};
 const chooseType=(kind:"company"|"individual"|"complimentary")=>setState(s=>({...s,accessType:(kind==="company"?"company":"individual") as AssessmentAccessType,fundingType:(kind==="complimentary"?"complimentary":"paid") as AssessmentFundingType,issuanceType:kind==="complimentary"?"complimentary":kind==="individual"?"online-paid":"offline-paid",reportVisibility:kind==="company"?"manager-only":"participant-only"}));
 async function submit(mode:"preview"|"execute"){
  if(!assessment)return; const id=operationId||crypto.randomUUID();if(!operationId)setOperationId(id);setBusy(true);setActionError("");
  const company=state.accessType==="company"; const endpoint=company?"/api/admin/actions/assessment-access/company/issue":"/api/admin/actions/assessment-access/individual/issue";
  const body=company?{mode,operationId:id,existingCompanyId:state.existingCompanyId||null,assessmentDefinitionId:assessment.id,assessmentDefinitionVersion:assessment.version,companyName:state.companyName,managerName:state.managerName,managerEmail:state.managerEmail,credits:Number(state.credits),commercialReference:state.commercialReference,reportVisibility:state.reportVisibility,issuanceType:state.issuanceType,languageMode:state.languageMode,expiresAt:state.expiresAt||null}:{mode,operationId:id,assessmentDefinitionId:assessment.id,assessmentDefinitionVersion:assessment.version,participantName:state.participantName,participantEmail:state.participantEmail,fundingType:state.fundingType,issuanceType:state.issuanceType,reportVisibility:state.reportVisibility,languageMode:state.languageMode,expiresAt:state.expiresAt||null,reason:state.commercialReference};
  try{const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok||!result.ok){setActionError(result?.error?.message||"Access could not be issued.");return;}if(mode==="preview"){setPreview(result.data.dryRun);setConfirm(true);}else{setIssued(result.data);setConfirm(false);toast.success("Assessment access issued.");}}catch{setActionError("Access could not be issued. Please try again.");}finally{setBusy(false);}
 }
 const copy=async(value:string,label:string)=>{await navigator.clipboard.writeText(value.startsWith("http")?value:`${window.location.origin}${value}`);toast.success(`${label} copied.`);};
 const next=()=>{const found=validateAssessmentAccessWizardStep(step,state,assessments);setErrors(found);if(!Object.keys(found).length)setStep(s=>Math.min(5,s+1));};
 if(!started)return <div className="space-y-7"><section className="rounded-3xl bg-slate-950 p-8 text-white"><Badge className="bg-blue-500/20">Unified Issuance</Badge><h1 className="mt-5 text-4xl font-black">Assessment Access Center</h1><p className="mt-3 max-w-2xl text-slate-300">Issue company, individual paid, and complimentary access through the existing production token, credit, and report authorization architecture.</p><Button onClick={()=>setStarted(true)} className="mt-7 bg-blue-600"><KeyRound className="mr-2 h-5 w-5"/>Issue Assessment</Button></section><div className="grid gap-4 sm:grid-cols-3">{[["Company / Team","One team link, manager dashboard, and credit wallet."],["Individual paid","One named single-use link without a company package."],["Complimentary","Audited free access with no company credit consumed."]].map(([title,description])=><Card key={title}><CardHeader><CardTitle className="text-base">{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader></Card>)}</div></div>;
 return <div className="mx-auto max-w-5xl space-y-6"><header><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Assessment Access</p><h1 className="mt-2 text-3xl font-black">Issue Assessment</h1></header><nav className="overflow-x-auto rounded-2xl border bg-white p-3"><ol className="flex min-w-[700px] gap-2">{steps.map((label,index)=>{const n=index+1;return <li className="flex-1" key={label}><span className={`flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-bold ${n===step?"bg-blue-600 text-white":n<step?"bg-emerald-50 text-emerald-800":"text-slate-500"}`}><span>{n<step?<Check className="h-4 w-4"/>:n}</span>{label}</span></li>;})}</ol></nav><Card><CardHeader><CardTitle>{steps[step-1]}</CardTitle><CardDescription>Review each setting carefully; no write occurs until final confirmation.</CardDescription></CardHeader><CardContent className="space-y-6">
 {step===1&&<div className="grid gap-3 md:grid-cols-2">{assessments.map(a=><button key={a.id} onClick={()=>update("assessmentId",a.id)} className={`rounded-2xl border p-5 text-left ${state.assessmentId===a.id?"border-blue-600 bg-blue-50":""}`}><span className="font-black">{a.name}</span><span className="mt-1 block text-xs text-slate-500">/{a.slug} · v{a.version}</span><span className="mt-3 flex gap-2">{a.companyAvailable&&<Badge variant="outline">Company</Badge>}{a.individualAvailable&&<Badge variant="outline">Individual</Badge>}{a.complimentaryAvailable&&<Badge variant="outline">Complimentary</Badge>}</span></button>)}<ErrorText message={errors.assessmentId}/></div>}
 {step===2&&<RadioGroup className="grid gap-4 md:grid-cols-3" value={state.accessType==="company"?"company":state.fundingType==="complimentary"?"complimentary":"individual"} onValueChange={v=>chooseType(v as any)}>{(["company","individual","complimentary"] as const).map(kind=>{const available=kind==="company"?assessment?.companyAvailable:kind==="individual"?assessment?.individualAvailable:assessment?.individualAvailable&&assessment?.complimentaryAvailable;const Icon=kind==="company"?Building2:UserRound;return <Label key={kind} className={`min-h-36 rounded-2xl border p-5 ${available?"cursor-pointer":"cursor-not-allowed bg-slate-50 text-slate-400"}`}><RadioGroupItem value={kind} disabled={!available}/><Icon className="mt-4 h-6 w-6"/><span className="mt-2 block text-lg font-black capitalize">{kind}</span></Label>})}<ErrorText message={errors.accessType}/></RadioGroup>}
 {step===3&&state.accessType==="company"&&<div className="grid gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Label className="font-bold">Existing Company (optional)</Label><Select value={state.existingCompanyId||"new"} onValueChange={id=>{const c=companies.find(item=>item.id===id);setState(s=>c?{...s,existingCompanyId:c.id,companyName:c.name,managerName:c.manager_name||"",managerEmail:c.billing_email,credits:""}:{...s,existingCompanyId:"",companyName:"",managerName:"",managerEmail:"",credits:""});setErrors({});setPreview(null);setIssued(null);}}><SelectTrigger className="mt-2 h-auto min-h-11 py-2 text-left"><SelectValue placeholder="Create a new company or select an existing one">{selectedCompany?`${selectedCompany.name} · ${selectedCompany.billing_email} · ${selectedCompany.credits_balance}/${selectedCompany.package_size} credits`:"Create a new company"}</SelectValue></SelectTrigger><SelectContent className="z-[100] max-h-80 w-[min(40rem,calc(100vw-2rem))] border-slate-200 bg-white shadow-2xl" viewportClassName="!h-auto max-h-72 overflow-y-auto p-1"><SelectItem value="new" className="py-3 font-semibold">Create a new company</SelectItem>{companies.map(c=><SelectItem key={c.id} value={c.id} textValue={`${c.name} ${c.manager_name||""} ${c.billing_email} ${c.credits_balance} of ${c.package_size} credits`} className="py-2.5"><span className="block min-w-0 whitespace-normal pr-3"><span className="block break-words font-semibold text-slate-950">{c.name}</span><span className="mt-0.5 block break-all text-xs text-slate-600">{c.manager_name?`${c.manager_name} · `:""}{c.billing_email} · {c.credits_balance}/{c.package_size} credits available</span></span></SelectItem>)}</SelectContent></Select>{selectedCompany&&<div className="mt-3 grid gap-3 rounded-xl border bg-slate-50 p-4 sm:grid-cols-2"><Row label="Current package" value={selectedCompany.package_size}/><Row label="Available credits" value={selectedCompany.credits_balance}/></div>}<ErrorText message={errors.existingCompanyId}/></div><Field id="company" label="Company Name" value={state.companyName} onChange={v=>update("companyName",v)} error={errors.companyName} disabled={!!selectedCompany}/><Field id="manager" label="Manager Name" value={state.managerName} onChange={v=>update("managerName",v)} error={errors.managerName} disabled={!!selectedCompany?.manager_name}/><Field id="manager-email" label="Manager Email" type="email" value={state.managerEmail} onChange={v=>update("managerEmail",v)} error={errors.managerEmail} disabled={!!selectedCompany}/><Field id="credits" label={selectedCompany?"Additional Credits / Seats":"Credits / Seats"} type="number" value={state.credits} onChange={v=>update("credits",v)} error={errors.credits}/><div className="sm:col-span-2"><Field id="reference" label="Mandatory Reason / Commercial Reference" value={state.commercialReference} onChange={v=>update("commercialReference",v)} error={errors.commercialReference}/></div></div>}
 {step===3&&state.accessType==="individual"&&<div className="grid gap-5 sm:grid-cols-2"><Field id="participant" label="Participant Name" value={state.participantName} onChange={v=>update("participantName",v)} error={errors.participantName}/><Field id="participant-email" label="Participant Email" type="email" value={state.participantEmail} onChange={v=>update("participantEmail",v)} error={errors.participantEmail}/><div><Label className="font-bold">Issuance Type</Label><Select value={state.issuanceType} onValueChange={v=>update("issuanceType",v as any)} disabled={state.fundingType==="complimentary"}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="online-paid">Online paid</SelectItem><SelectItem value="offline-paid">Offline / manually paid</SelectItem><SelectItem value="complimentary">Complimentary</SelectItem></SelectContent></Select><ErrorText message={errors.issuanceType}/></div><div><Label className="font-bold">Language</Label><Select value={state.languageMode} onValueChange={v=>update("languageMode",v as any)}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="participant-choice">Participant chooses English / Arabic</SelectItem><SelectItem value="en">Force English</SelectItem><SelectItem value="ar">Force Arabic</SelectItem></SelectContent></Select></div><Field id="expiry" label="Optional Expiry" type="datetime-local" value={state.expiresAt} onChange={v=>update("expiresAt",v)}/><div className="sm:col-span-2"><Field id="reason" label="Mandatory Reason / Issuance Note" value={state.commercialReference} onChange={v=>update("commercialReference",v)} error={errors.commercialReference}/></div></div>}
 {step===4&&<div className="grid max-w-3xl gap-5 sm:grid-cols-2"><div className="sm:col-span-2"><Label className="font-bold">Report Visibility</Label><Select value={state.reportVisibility} onValueChange={v=>update("reportVisibility",v as AssessmentReportVisibility)}><SelectTrigger className="mt-2"><SelectValue placeholder="Select visibility"/></SelectTrigger><SelectContent>{ASSESSMENT_REPORT_VISIBILITIES.map(v=><SelectItem key={v} value={v}>{labels[v]}</SelectItem>)}</SelectContent></Select><p className="mt-2 text-sm text-slate-500">Stored per issuance and enforced server-side.</p><ErrorText message={errors.reportVisibility}/></div>{state.accessType==="company"&&<><div><Label className="font-bold">Issuance Type</Label><Select value={state.issuanceType} onValueChange={v=>update("issuanceType",v as any)}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="offline-paid">Offline / manually sold</SelectItem><SelectItem value="online-paid">Online</SelectItem><SelectItem value="complimentary">Complimentary company package</SelectItem></SelectContent></Select></div><div><Label className="font-bold">Language</Label><Select value={state.languageMode} onValueChange={v=>update("languageMode",v as any)}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="participant-choice">Participant chooses English / Arabic</SelectItem><SelectItem value="en">Force English</SelectItem><SelectItem value="ar">Force Arabic</SelectItem></SelectContent></Select></div><Field id="company-expiry" label="Optional Expiry" type="datetime-local" value={state.expiresAt} onChange={v=>update("expiresAt",v)}/></>}</div>}
 {step===5&&<div className="space-y-5"><dl className="rounded-2xl border bg-slate-50 px-5"><Row label="Recipient" value={state.accessType==="company"?"Company / Team":state.fundingType==="complimentary"?"Complimentary":"Individual"}/><Row label="Assessment" value={assessment?.name}/><Row label="Company / Participant" value={state.accessType==="company"?state.companyName:`${state.participantName} · ${state.participantEmail}`}/><Row label="Manager" value={state.accessType==="company"?`${state.managerName} · ${state.managerEmail}`:""}/><Row label="Credits" value={state.accessType==="company"?state.credits:""}/><Row label="Language" value={state.languageMode}/><Row label="Report Visibility" value={labels[state.reportVisibility]}/><Row label="Reason / Reference" value={state.commercialReference}/></dl>{issued?<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p className="font-black text-emerald-950">Assessment access issued</p><p className="mt-1 text-sm text-emerald-800">Policy and audit records were saved.</p><div className="mt-4 flex flex-wrap gap-2">{issued.employeeAssessmentPath&&<Button variant="outline" onClick={()=>copy(issued.employeeAssessmentPath!,"Participant link")}><Copy className="mr-2 h-4 w-4"/>Copy Participant Link</Button>}{issued.assessmentUrl&&<Button variant="outline" onClick={()=>copy(issued.assessmentUrl!,"Participant link")}><Copy className="mr-2 h-4 w-4"/>Copy Participant Link</Button>}{issued.managerDashboardPath&&<Button variant="outline" onClick={()=>copy(issued.managerDashboardPath!,"Manager link")}><Copy className="mr-2 h-4 w-4"/>Copy Manager Link</Button>}</div></div>:<div className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><p className="font-black text-blue-950">Ready to preview</p>{actionError&&<ErrorText message={actionError}/>}<Button onClick={()=>submit("preview")} disabled={busy} className="mt-3 bg-blue-700">{busy?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:null}Preview Issuance</Button></div>}</div>}
 <div className="flex justify-between border-t pt-5"><Button variant="outline" onClick={()=>step===1?setStarted(false):setStep(s=>s-1)}><ArrowLeft className="mr-2 h-4 w-4"/>Back</Button>{step<5&&<Button onClick={next} className="bg-slate-950">Continue<ArrowRight className="ml-2 h-4 w-4"/></Button>}</div></CardContent></Card><Dialog open={confirm} onOpenChange={setConfirm}><DialogContent><DialogHeader><DialogTitle>Generate live assessment access?</DialogTitle><DialogDescription>This creates a live credential and immutable audit record.</DialogDescription></DialogHeader>{preview&&<><dl className="rounded-xl border px-4">{Object.entries(preview.expectedResult).map(([k,v])=><Row key={k} label={k} value={v}/>)}</dl><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm">{preview.warnings.map(w=><p key={w}>{w}</p>)}</div></>}<DialogFooter><Button variant="outline" onClick={()=>setConfirm(false)}>Cancel</Button><Button onClick={()=>submit("execute")} disabled={busy} className="bg-rose-700">Confirm and Generate Access</Button></DialogFooter></DialogContent></Dialog></div>;
}
