import Link from "next/link";
import { ArrowRight, Clock3, FileSearch, Gift, Search } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { ComplimentaryAssessment } from "@/modules/complimentary/complimentary-access-service";

export function ComplimentaryHome({ result }: { result: { search: string; assessments: ComplimentaryAssessment[] } }) {
  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-700">Complimentary Access Center</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">Assessment Access Readiness</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Review eligibility and generate governed individual complimentary access.</p></div><Badge variant="outline" className="w-fit border-blue-200 bg-blue-50 px-3 py-1.5 text-blue-800">{result.assessments.length} registered assessments</Badge></div>
    <Card className="border-slate-200 shadow-sm"><CardContent className="p-4 sm:p-5"><form method="get" className="flex flex-col gap-3 sm:flex-row" aria-label="Search assessments"><div className="relative flex-1"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" aria-hidden="true" /><Input name="q" defaultValue={result.search} placeholder="Search assessment or status" className="pl-9" aria-label="Search registered assessments" /></div><Button type="submit" className="bg-slate-950">Search</Button></form></CardContent></Card>
    {result.assessments.length ? <div className="grid gap-5 md:grid-cols-2 2xl:grid-cols-3">{result.assessments.map((assessment) => <Card key={assessment.id} className="flex flex-col border-slate-200 shadow-sm"><CardHeader><div className="flex items-start justify-between gap-4"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-slate-950 text-white"><Gift className="h-5 w-5" aria-hidden="true" /></span><Badge variant="outline" className={assessment.status.toLocaleLowerCase() === "active" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-slate-200 bg-slate-50 text-slate-700"}>{assessment.status}</Badge></div><CardTitle className="pt-3 text-xl">{assessment.name}</CardTitle><code className="text-xs text-slate-500">/{assessment.slug}</code></CardHeader><CardContent className="flex flex-1 flex-col"><dl className="space-y-3 text-sm"><div><dt className="font-semibold text-slate-500">Individual Availability</dt><dd className="mt-1 font-bold">{assessment.individualAvailability}</dd></div><div><dt className="font-semibold text-slate-500">Corporate Availability</dt><dd className="mt-1 font-bold">{assessment.corporateAvailability}</dd></div><div><dt className="font-semibold text-slate-500">Complimentary Capability</dt><dd className="mt-1 font-bold text-amber-700">{assessment.complimentaryCapability}</dd></div></dl><div className="mt-auto grid grid-cols-2 gap-2 pt-6"><Button asChild disabled={assessment.complimentaryCapability !== "Available"} className="col-span-2 gap-2"><Link href={`/admin/complimentary/${encodeURIComponent(assessment.slug)}`}><Gift className="h-4 w-4" aria-hidden="true" />Generate Complimentary Token</Link></Button><Button asChild variant="outline" size="sm"><Link href={`/admin/complimentary/${encodeURIComponent(assessment.slug)}#history`}><Clock3 className="mr-2 h-4 w-4" aria-hidden="true" />History</Link></Button><Button asChild variant="outline" size="sm"><Link href={`/admin/complimentary/${encodeURIComponent(assessment.slug)}`}>Details <ArrowRight className="ml-2 h-4 w-4" aria-hidden="true" /></Link></Button></div><p className="mt-3 text-center text-xs text-slate-500">Requires permission, preview, and confirmation.</p></CardContent></Card>)}</div> : <Card className="border-dashed"><CardContent className="flex min-h-64 flex-col items-center justify-center text-center"><FileSearch className="h-10 w-10 text-slate-300" aria-hidden="true" /><h2 className="mt-4 text-lg font-black">No assessments found</h2><p className="mt-2 text-sm text-slate-500">Try a different assessment name, slug, or status.</p></CardContent></Card>}
  </div>;
}
