import Link from "next/link";
import { ArrowLeft, Gift, History, Search, ShieldCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ComplimentaryFutureActions } from "@/components/admin/complimentary-future-actions";
import type { ComplimentaryAssessmentDetail } from "@/modules/complimentary/complimentary-access-service";

function dateLabel(value: string | null) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" }).format(date); }
function Fact({ label, children }: { label: string; children: React.ReactNode }) { return <div className="border-b border-slate-100 py-3 last:border-0 sm:grid sm:grid-cols-[190px_1fr] sm:gap-4"><dt className="text-sm font-semibold text-slate-500">{label}</dt><dd className="mt-1 text-sm font-bold sm:mt-0">{children}</dd></div>; }
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-2xl font-black tabular-nums">{value}</p></div>; }

export function ComplimentaryDetail({ detail }: { detail: ComplimentaryAssessmentDetail }) {
  return <div className="space-y-7">
    <div><Button asChild variant="ghost" size="sm" className="-ms-3 mb-3 gap-2 text-slate-600"><Link href="/admin/complimentary"><ArrowLeft className="h-4 w-4" aria-hidden="true" />Back to complimentary access</Link></Button><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div className="flex items-start gap-4"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-slate-950 text-white shadow-lg"><Gift className="h-6 w-6" aria-hidden="true" /></span><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-700">Complimentary readiness</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">{detail.name}</h1><code className="mt-2 block text-sm text-slate-500">/{detail.slug}</code></div></div><Badge variant="outline" className={detail.status.toLocaleLowerCase() === "active" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-slate-200 bg-slate-50 text-slate-700"}>{detail.status}</Badge></div></div>
    <section className="grid gap-6 xl:grid-cols-2"><Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle>Assessment access profile</CardTitle></CardHeader><CardContent><dl><Fact label="Assessment">{detail.name}</Fact><Fact label="Slug">{detail.slug}</Fact><Fact label="Status">{detail.status}</Fact><Fact label="Languages">{detail.languages.join(", ")}</Fact><Fact label="Current Access Model">{detail.currentAccessModel}</Fact><Fact label="Individual Flow">{detail.individualFlow}</Fact><Fact label="Corporate Flow">{detail.corporateFlow}</Fact><Fact label="Token Requirement">{detail.tokenRequirement}</Fact><Fact label="Complimentary Capability"><span className="text-amber-700">{detail.complimentaryCapability}</span></Fact></dl></CardContent></Card><Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-blue-700" aria-hidden="true" />Complimentary token statistics</CardTitle></CardHeader><CardContent><div className="grid grid-cols-2 gap-3"><Stat label="Total" value={detail.statistics.total} /><Stat label="Active" value={detail.statistics.active} /><Stat label="Used" value={detail.statistics.used} /><Stat label="Expired" value={detail.statistics.expired} /></div><p className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm leading-6 text-blue-900">Statistics include only explicitly typed complimentary entitlements. Company access tokens remain excluded.</p></CardContent></Card></section>
    <section id="history" aria-labelledby="history-title" className="scroll-mt-6 space-y-4"><div><h2 id="history-title" className="flex items-center gap-2 text-xl font-black"><History className="h-5 w-5 text-blue-700" aria-hidden="true" />Complimentary access history</h2><p className="mt-1 text-sm text-slate-500">Search and filters inspect the typed complimentary entitlement history.</p></div><Card className="border-slate-200 shadow-sm"><CardContent className="p-4 sm:p-5"><form method="get" action={`/admin/complimentary/${encodeURIComponent(detail.slug)}`} className="grid gap-3 sm:grid-cols-[minmax(240px,1fr)_180px_auto]" aria-label="Search complimentary history"><div className="relative"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400" aria-hidden="true" /><Input name="q" defaultValue={detail.search} placeholder="Assessment, email, token ID, or status" className="pl-9" aria-label="Search complimentary history" /></div><select name="filter" defaultValue={detail.filter} className="h-10 rounded-md border border-input bg-background px-3 text-sm" aria-label="Filter complimentary history"><option value="all">All</option><option value="active">Active</option><option value="used">Used</option><option value="expired">Expired</option></select><Button type="submit" className="bg-slate-950">Apply</Button></form></CardContent></Card>
      {detail.tokens.length ? <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><Table><TableHeader><TableRow className="bg-slate-50"><TableHead>Created</TableHead><TableHead>Expires</TableHead><TableHead>Used</TableHead><TableHead>Assessment</TableHead><TableHead>Email</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{detail.tokens.map((token) => <TableRow key={token.id}><TableCell>{dateLabel(token.createdAt)}</TableCell><TableCell>{dateLabel(token.expiresAt)}</TableCell><TableCell>{dateLabel(token.usedAt)}</TableCell><TableCell>{token.assessment}</TableCell><TableCell>{token.email || "—"}</TableCell><TableCell><Badge variant="outline">{token.status}</Badge></TableCell></TableRow>)}</TableBody></Table></div> : <Card className="border-dashed"><CardContent className="flex min-h-48 flex-col items-center justify-center text-center"><History className="h-9 w-9 text-slate-300" aria-hidden="true" /><p className="mt-4 font-bold">No complimentary access history found.</p></CardContent></Card>}
    </section>
    <ComplimentaryFutureActions assessmentId={detail.id} assessmentName={detail.name} eligible={detail.status.toLocaleLowerCase() === "active" && detail.complimentaryCapability === "Available"} />
  </div>;
}
