import Link from "next/link";
import { ArrowLeft, Building2, ExternalLink, History, Mail } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CreditFutureActions } from "@/components/admin/credit-future-actions";
import type { CreditDetail as CreditDetailModel } from "@/modules/credits/credit-service";

function dateLabel(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "—" : new Intl.DateTimeFormat("en-GB", { day: "2-digit", month: "short", year: "numeric" }).format(date); }
function Metric({ label, value }: { label: string; value: number }) { return <Card className="border-slate-200 shadow-sm"><CardContent className="p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">{label}</p><p className="mt-2 text-3xl font-black tabular-nums">{value}</p></CardContent></Card>; }
function Fact({ label, children }: { label: string; children: React.ReactNode }) { return <div className="border-b border-slate-100 py-3 last:border-0 sm:grid sm:grid-cols-[170px_1fr] sm:gap-4"><dt className="text-sm font-semibold text-slate-500">{label}</dt><dd className="mt-1 text-sm font-bold sm:mt-0">{children}</dd></div>; }

export function CreditDetail({ credit }: { credit: CreditDetailModel }) {
  return <div className="space-y-7">
    <div><Button asChild variant="ghost" size="sm" className="-ms-3 mb-3 gap-2 text-slate-600"><Link href="/admin/credits"><ArrowLeft className="h-4 w-4" aria-hidden="true" />Back to credits</Link></Button><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div className="flex items-start gap-4"><span className="flex h-14 w-14 shrink-0 items-center justify-center rounded-2xl bg-slate-950 text-white shadow-lg"><Building2 className="h-6 w-6" aria-hidden="true" /></span><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-blue-700">Credit account</p><h1 className="mt-1 text-3xl font-black tracking-tight sm:text-4xl">{credit.company}</h1><p className="mt-2 flex items-center gap-2 text-sm text-slate-600"><Mail className="h-4 w-4" aria-hidden="true" />{credit.manager}</p></div></div><Badge variant="outline" className={credit.creditsRemaining > 0 ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-amber-200 bg-amber-50 text-amber-800"}>{credit.status}</Badge></div></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Credit metrics"><Metric label="Package Size" value={credit.packageSize} /><Metric label="Purchased" value={credit.creditsPurchased} /><Metric label="Used" value={credit.creditsUsed} /><Metric label="Remaining" value={credit.creditsRemaining} /></section>
    <section className="grid gap-6 xl:grid-cols-2">
      <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle>Company profile</CardTitle></CardHeader><CardContent><dl><Fact label="Company">{credit.company}</Fact><Fact label="Assessment">{credit.assessment}</Fact><Fact label="Manager">{credit.manager}</Fact><Fact label="Created">{dateLabel(credit.createdAt)}</Fact><Fact label="Dashboard Link">{credit.managerDashboardPath ? <Button asChild variant="outline" size="sm" className="gap-2"><Link href={credit.managerDashboardPath} target="_blank" rel="noreferrer">Open dashboard <ExternalLink className="h-4 w-4" aria-hidden="true" /></Link></Button> : "Not configured"}</Fact></dl></CardContent></Card>
      <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2"><History className="h-5 w-5 text-blue-700" aria-hidden="true" />Credit history summary</CardTitle></CardHeader><CardContent>{credit.history.length ? <div className="space-y-4"><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-500">Ledger entries</p><p className="mt-1 text-2xl font-black">{credit.history.length}</p></div><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase text-slate-500">Net change</p><p className="mt-1 text-2xl font-black tabular-nums">{credit.historyNetChange > 0 ? "+" : ""}{credit.historyNetChange}</p></div></div><ul className="space-y-2">{credit.history.slice(0, 10).map((entry, index) => <li key={`${entry.description}-${index}`} className="flex items-start justify-between gap-4 rounded-xl border border-slate-100 px-4 py-3"><span className="text-sm text-slate-700">{entry.description}</span><span className={`shrink-0 font-black tabular-nums ${entry.amount < 0 ? "text-rose-700" : "text-emerald-700"}`}>{entry.amount > 0 ? "+" : ""}{entry.amount}</span></li>)}</ul><p className="text-xs text-slate-500">The available ledger has no documented event timestamp, so entries are not presented as chronological.</p></div> : <p className="text-sm text-slate-500">No readable credit history is available for this company.</p>}</CardContent></Card>
    </section>
    <CreditFutureActions companyId={credit.companyId} companyName={credit.company} canRestore={credit.creditsRemaining < credit.packageSize} />
  </div>;
}
